[package]
name = "keyauth"
version = "0.1.0"
authors = ["zegevlier <iamascratcher@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version= "0.8.1", features = ["v4"] }
rust-crypto = "0.2.36"
reqwest = { version = "0.10.9", features = ["blocking"] }
hex = "0.4.2"
aes = "0.6.0"
block-modes = "0.7.0"
base16 = "0.2.1"
machine_uuid = "0.1.0"