[package]
authors = ["zegevlier <iamascratcher@gmail.com>"]
edition = "2018"
name = "keyauth"
version = "0.2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.6.0"
base16 = "0.2.1"
block-modes = "0.7.0"
hex = "0.4.2"
machine_uuid = "0.1.0"
obfstr = "0.2.1"
reqwest = {version = "0.10.10", features = ["blocking"]}
rust-crypto = "0.2.36"
serde = {version = "1.0.118", features = ["derive"]}
serde_json = "1.0.61"
uuid = {version = "0.8.1", features = ["v4"]}
